### ISSUE TITLE
replace a value

### ISSUE THREAD

**Issue by 1312Bravo** [1312Bravo/APPR-2018-19#2]
Zdravo,
v tabeli 'st. igralcev', želim Bosnia and Herzegovina preimenovati v Bosnia and Herz.
poskusil sem: st.igralcev[2,1] <- "Bosnia and Herz."
R mi vrne error, ne razumem kaj je narobe.
Hvala, lp.

**Comment by MarvinHerzog** [comment]
Zdravo, nekaj stvari:

V *uvoz.r* zamenjaj 
```uvozi.populacijo <- function(populacija) {```
 z 
```uvozi.populacijo <- function() {```,
 saj te funkcije ne kličeš s parametrom in ti javlja napako.

V *analiza.r* kličeš data.frame evropejci, vendar ga pred tem ne naložiš v okolje. Da to narediš, na začetek skripte dodaj `source("uvoz/uvoz.r")

V `uvoz.R` imaš vrstici (ki sta podvojeni malo nižje)
```
evropske_drzave <- populacija$Country
evropejci <- filter(tujci, Country %in% evropske_drzave)
```
vendar definiraš objekt `populacija` šele nekaj vrstic kasneje


Glede napake, ki se ti pojavi v issue:
Pri sebi v tabeli `st.igralcev` sicer nimam Bosne, vendar sklepam da vnosa ne moreš preimenovati, ker je faktor - torej, urejenostna spremenljivka. Problem se pojavi ko želiš dodati vnos, ki ni med trenutnimi nivoji faktorja. Temu se lahko izogneš tako da (začasno) spremeniš prvi stolpec v character tip in nato preimenuješ vrstico:

```
st.igralcev[,1] <- as.character(st.igralcev[,1])
st.igralcev[2,1] <- "Bosnia and Herz."
```

na koncu pa lahko še po želji stolpec spet spremeniš v faktor, ki bo zdaj imel nov vnos kot dodan nivo.
```
st.igralcev[,1] <- as.factor(st.igralcev[,1])
```
